package edu.wctc;

import org.apache.commons.codec.language.Soundex;

public class LastNameUtility {
     /*
    If the last name is blank, throws a MissingNameException.
    Returns the encoding of the last name generated by the Soundex algorithm.
    Slides 86 though 90 for Soundex from Mod 5 slides
     */

    private Soundex soundex;
    private String enc;

    public String encodeLastName(String lastName) throws MissingNameException {
        Soundex soundex = new Soundex();


        if (lastName.isBlank()) {
            throw new MissingNameException(lastName);
        } else {
            return (enc = soundex.encode(lastName));

        }
    }
}
